const fs = require('fs');
const path = require('path');

function safeRound(num, decimals = 2) {
  const factor = Math.pow(10, decimals);
  return Math.round((num + Number.EPSILON) * factor) / factor;
}

// 1. Settings
const settings = {
  company_name: 'DAILY COLLECTION',
  company_tagline: 'Daily Collection System',
  company_address: 'Mount Road, Chennai - 600002, Tamil Nadu',
  company_phone: '+91 94432 10001',
  company_email: 'support@dailycollection.com',
  company_logo: '',
  receipt_prefix: 'DC-REC-',
  currency: '₹',
  default_collection_days: 100,
  default_payment_mode: 'Cash',
  notifications_enabled: true,
};

// 2. Collectors
const collectors = [
  {
    id: 'COL101',
    name: 'Murugan S.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    mobile: '98421 11223',
    email: 'murugan.s@krsfinance.com',
    address: '22, Anna Nagar, Salem - 636004',
    assigned_area: 'Bazaar Main Road',
    joining_date: '2025-06-01',
    target_amount: 35000,
    status: 'ACTIVE',
  },
  {
    id: 'COL102',
    name: 'Karthik Raja',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    mobile: '98422 33445',
    email: 'karthik.raja@krsfinance.com',
    address: '15, Gandhi Road, Salem - 636001',
    assigned_area: 'Town Hall Road',
    joining_date: '2025-08-15',
    target_amount: 30000,
    status: 'ACTIVE',
  },
  {
    id: 'COL103',
    name: 'Saravanan P.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    mobile: '98423 55667',
    email: 'saravanan.p@krsfinance.com',
    address: '88, Periyar Street, Salem - 636002',
    assigned_area: 'Car Street',
    joining_date: '2025-09-01',
    target_amount: 30000,
    status: 'ACTIVE',
  },
];

// 3. Areas
const areas = [
  {
    id: 'AREA101',
    area_name: 'Bazaar Main Road',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    assigned_collector_id: 'COL101',
    assigned_collector_name: 'Murugan S.',
    customer_count: 8,
  },
  {
    id: 'AREA102',
    area_name: 'Town Hall Road',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    assigned_collector_id: 'COL102',
    assigned_collector_name: 'Karthik Raja',
    customer_count: 7,
  },
  {
    id: 'AREA103',
    area_name: 'Car Street',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    assigned_collector_id: 'COL103',
    assigned_collector_name: 'Saravanan P.',
    customer_count: 6,
  },
  {
    id: 'AREA104',
    area_name: 'Market Gate',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    assigned_collector_id: 'COL101',
    assigned_collector_name: 'Murugan S.',
    customer_count: 5,
  },
  {
    id: 'AREA105',
    area_name: 'New Bus Stand Area',
    city: 'Salem',
    district: 'Salem',
    pincode: '636004',
    assigned_collector_id: 'COL102',
    assigned_collector_name: 'Karthik Raja',
    customer_count: 4,
  },
];

// 4. Collection Plans
const collection_plans = [
  {
    id: 'PLAN100_10K',
    plan_name: 'Standard 100-Day Plan (₹10,000)',
    requested_amount: 10000,
    disbursed_amount: 8800,
    daily_collection: 100,
    collection_days: 100,
    total_repayment: 10000,
    finance_margin: 1200,
    status: 'ACTIVE',
    description: 'Standard Daily Collection plan: ₹10,000 requested → ₹8,800 disbursed → ₹100 × 100 days → ₹10,000 collected → ₹1,200 margin.',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'PLAN100_20K',
    plan_name: 'Silver 100-Day Plan (₹20,000)',
    requested_amount: 20000,
    disbursed_amount: 17600,
    daily_collection: 200,
    collection_days: 100,
    total_repayment: 20000,
    finance_margin: 2400,
    status: 'ACTIVE',
    description: 'High volume plan: ₹20,000 requested → ₹17,600 disbursed → ₹200 × 100 days → ₹20,000 collected → ₹2,400 margin.',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'PLAN100_50K',
    plan_name: 'Gold 100-Day Plan (₹50,000)',
    requested_amount: 50000,
    disbursed_amount: 44000,
    daily_collection: 500,
    collection_days: 100,
    total_repayment: 50000,
    finance_margin: 6000,
    status: 'ACTIVE',
    description: 'Premium business plan: ₹50,000 requested → ₹44,000 disbursed → ₹500 × 100 days → ₹50,000 collected → ₹6,000 margin.',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'PLAN50_10K',
    plan_name: 'Express 50-Day Plan (₹10,000)',
    requested_amount: 10000,
    disbursed_amount: 9000,
    daily_collection: 200,
    collection_days: 50,
    total_repayment: 10000,
    finance_margin: 1000,
    status: 'ACTIVE',
    description: 'Short cycle plan: ₹10,000 requested → ₹9,000 disbursed → ₹200 × 50 days → ₹10,000 collected → ₹1,000 margin.',
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

// Raw definition of 30 retail customers with rich metadata
const customerDefinitions = [
  {
    id: 'KRS10001',
    name: 'Ramesh Kumar',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    gender: 'Male',
    dob: '1985-05-14',
    father_or_husband: 'Shanmugam K.',
    mother: 'Lakshmi S.',
    marital: 'Married',
    mobile: '9876543210',
    email: 'ramesh.kumar@gmail.com',
    door: '12/4',
    street: 'Agraharam North Street',
    area: 'Shevapet',
    town: 'Salem Town',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Kottai Mariamman Temple',
    shop_name: 'Sri Krishna Supermarket & Provisions',
    biz_type: 'Grocery & Provisions Retail',
    biz_cat: 'FMCG / Daily Essentials',
    shop_addr: 'No. 18, Bazaar Main Road',
    shop_area: 'Bazaar Main Road',
    shop_pincode: '636001',
    shop_landmark: 'Opposite Clock Tower',
    years_biz: 12,
    income: 95000,
    sales: 18000,
    shop_photo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10002',
    name: 'Sundar Rajan',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'Male',
    dob: '1982-11-20',
    father_or_husband: 'Ramasamy T.',
    mother: 'Parvathi R.',
    marital: 'Married',
    mobile: '9842211990',
    email: 'sundar.bakery@gmail.com',
    door: '45-B',
    street: 'Muniyappan Koil Street',
    area: 'Gugai',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636006',
    landmark: 'Behind Gugai Girls High School',
    shop_name: 'Annapoorna Sweets, Bakery & Snacks',
    biz_type: 'Bakery & Sweets',
    biz_cat: 'Food & Confectionery',
    shop_addr: 'No. 54, Town Hall Road',
    shop_area: 'Town Hall Road',
    shop_pincode: '636001',
    shop_landmark: 'Near Victoria Hall',
    years_biz: 16,
    income: 140000,
    sales: 24000,
    shop_photo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10003',
    name: 'Meenakshi Ammal',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    gender: 'Female',
    dob: '1979-08-04',
    father_or_husband: 'Late Narayanan V.',
    mother: 'Valli N.',
    marital: 'Other',
    mobile: '9842377881',
    email: 'meenakshi.textiles@gmail.com',
    door: '78',
    street: 'Weavers Colony 2nd Cross',
    area: 'Ammapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636003',
    landmark: 'Opposite Ammapet Police Station',
    shop_name: 'Murugan Textiles, Sarees & Readymade',
    biz_type: 'Textiles & Garments',
    biz_cat: 'Apparel / Retail',
    shop_addr: 'No. 102, Car Street',
    shop_area: 'Car Street',
    shop_pincode: '636002',
    shop_landmark: 'Near Sugavaneswarar Temple Car Stand',
    years_biz: 20,
    income: 220000,
    sales: 38000,
    shop_photo: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500',
    plan_id: 'PLAN100_50K',
    start_date: '2026-07-01',
    collector_id: 'COL103',
    collector_name: 'Saravanan P.',
  },
  {
    id: 'KRS10004',
    name: 'Vijay Anand',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    gender: 'Male',
    dob: '1988-02-17',
    father_or_husband: 'Anandhan M.',
    mother: 'Kasthuri A.',
    marital: 'Married',
    mobile: '9842499001',
    email: 'vijay.paints@gmail.com',
    door: '3/110',
    street: 'Kamarajar Salai',
    area: 'Fairlands',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636016',
    landmark: 'Near Saradha College Roundana',
    shop_name: 'Anand Hardware, Paints & Electricals',
    biz_type: 'Hardware & Construction Tools',
    biz_cat: 'Retail & Commercial',
    shop_addr: 'No. 33, Market Gate Road',
    shop_area: 'Market Gate',
    shop_pincode: '636001',
    shop_landmark: 'Entry Gate No. 2, Old Market',
    years_biz: 8,
    income: 80000,
    sales: 15000,
    shop_photo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-06-15',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10005',
    name: 'Senthil Nathan',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    gender: 'Male',
    dob: '1991-09-29',
    father_or_husband: 'Chidambaram S.',
    mother: 'Meena C.',
    marital: 'Single',
    mobile: '9842544332',
    email: 'senthil.tea@gmail.com',
    door: '88/1',
    street: 'Meyyanur Main Road',
    area: 'Meyyanur',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636004',
    landmark: 'Near AVR Circle',
    shop_name: 'Nathan Tea Stall, Tiffin & Cool Drinks',
    biz_type: 'Tea Stall & Cafeteria',
    biz_cat: 'Beverage & Eatery',
    shop_addr: 'Platform Shop #4, Central Bus Terminus',
    shop_area: 'New Bus Stand Area',
    shop_pincode: '636004',
    shop_landmark: 'Opposite Bay 3, Mofussil Platform',
    years_biz: 5,
    income: 60000,
    sales: 12000,
    shop_photo: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500',
    plan_id: 'PLAN50_10K',
    start_date: '2026-07-15',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10006',
    name: 'Kavitha Selvam',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    gender: 'Female',
    dob: '1990-03-12',
    father_or_husband: 'Selvamurugan G.',
    mother: 'Deivanai S.',
    marital: 'Married',
    mobile: '9842666778',
    email: 'kavitha.fancy@gmail.com',
    door: '24',
    street: 'Kandhampatty Bypass Service Road',
    area: 'Kandhampatty',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636005',
    landmark: 'Next to Murugan Kalyana Mandapam',
    shop_name: 'Selvam Fancy Store, Toys & Stationeries',
    biz_type: 'Fancy Store & Gift Articles',
    biz_cat: 'Stationery & Novelties',
    shop_addr: 'No. 7, College Road',
    shop_area: 'Bazaar Main Road',
    shop_pincode: '636001',
    shop_landmark: 'Near Govt Arts College Gate',
    years_biz: 7,
    income: 55000,
    sales: 11000,
    shop_photo: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10007',
    name: 'Muthuraman K.',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    gender: 'Male',
    dob: '1983-04-18',
    father_or_husband: 'Krishnasamy P.',
    mother: 'Saraswathi K.',
    marital: 'Married',
    mobile: '9842711223',
    email: 'muthu.medicals@gmail.com',
    door: '19',
    street: 'First Agraharam',
    area: 'Shevapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Sri Venkateswara Temple',
    shop_name: 'Sri Lakshmi Medicals & Health Care',
    biz_type: 'Pharmacy & Healthcare',
    biz_cat: 'Medical & Pharmaceuticals',
    shop_addr: 'Shop 21, Town Hall Road',
    shop_area: 'Town Hall Road',
    shop_pincode: '636001',
    shop_landmark: 'Opposite Head Post Office',
    years_biz: 14,
    income: 125000,
    sales: 22000,
    shop_photo: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10008',
    name: 'Annamalai C.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    gender: 'Male',
    dob: '1987-07-22',
    father_or_husband: 'Chellappan M.',
    mother: 'Kannammal C.',
    marital: 'Married',
    mobile: '9842833445',
    email: 'annamalai.auto@gmail.com',
    door: '52',
    street: 'Old Market 2nd Lane',
    area: 'Car Street',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Behind Raja Talkies',
    shop_name: 'Balaji Automobiles & Two-Wheeler Spares',
    biz_type: 'Auto Spares & Lubricants',
    biz_cat: 'Automotive / Spares',
    shop_addr: 'No. 88, Car Street',
    shop_area: 'Car Street',
    shop_pincode: '636002',
    shop_landmark: 'Near Mariamman Temple Arch',
    years_biz: 9,
    income: 85000,
    sales: 16000,
    shop_photo: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL103',
    collector_name: 'Saravanan P.',
  },
  {
    id: 'KRS10009',
    name: 'Priya Dharshini',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    gender: 'Female',
    dob: '1993-12-05',
    father_or_husband: 'Dharmaraj S.',
    mother: 'Revathy D.',
    marital: 'Single',
    mobile: '9842955667',
    email: 'priya.bridal@gmail.com',
    door: '11/3',
    street: 'Kallanguthu 3rd Cross',
    area: 'Ammapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636003',
    landmark: 'Near CSI Christ Church',
    shop_name: 'Priya Bridal Studio & Tailoring',
    biz_type: 'Boutique & Tailoring Center',
    biz_cat: 'Fashion & Beauty',
    shop_addr: 'No. 14, Market Gate Road',
    shop_area: 'Market Gate',
    shop_pincode: '636001',
    shop_landmark: 'First Floor, Shanthi Complex',
    years_biz: 6,
    income: 70000,
    sales: 13000,
    shop_photo: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-10',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10010',
    name: 'Selva Ganesh',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'Male',
    dob: '1984-01-30',
    father_or_husband: 'Ganesan K.',
    mother: 'Malliga G.',
    marital: 'Married',
    mobile: '9843011224',
    email: 'ganesh.elec@gmail.com',
    door: '91',
    street: 'Swarnapuri Main Road',
    area: 'Fairlands',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636004',
    landmark: 'Near A2B Restaurant',
    shop_name: 'Ganesh Electricals & Home Appliances',
    biz_type: 'Electrical Goods & Lighting',
    biz_cat: 'Consumer Electronics',
    shop_addr: 'Shop 10, Bus Stand Complex',
    shop_area: 'New Bus Stand Area',
    shop_pincode: '636004',
    shop_landmark: 'Opposite State Express Stand',
    years_biz: 11,
    income: 110000,
    sales: 20000,
    shop_photo: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10011',
    name: 'Saravanan V.',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    gender: 'Male',
    dob: '1986-09-14',
    father_or_husband: 'Velusamy N.',
    mother: 'Chellammal V.',
    marital: 'Married',
    mobile: '9843122335',
    email: 'saravanan.provisions@gmail.com',
    door: '34/2',
    street: 'Pillaiyar Koil Street',
    area: 'Shevapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Old Water Tank',
    shop_name: 'Thirumalai Maligai & Provisions',
    biz_type: 'Wholesale & Retail Groceries',
    biz_cat: 'FMCG / Food Grain',
    shop_addr: 'No. 42, Bazaar Main Road',
    shop_area: 'Bazaar Main Road',
    shop_pincode: '636001',
    shop_landmark: 'Near Salem Old Bus Stand',
    years_biz: 13,
    income: 135000,
    sales: 26000,
    shop_photo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10012',
    name: 'Lakshmi Narayanan',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    gender: 'Male',
    dob: '1981-06-25',
    father_or_husband: 'Narayanasamy R.',
    mother: 'Kamalam N.',
    marital: 'Married',
    mobile: '9843233446',
    email: 'royal.footwear@gmail.com',
    door: '6/18',
    street: 'Gugai Main Road',
    area: 'Gugai',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636006',
    landmark: 'Near Gandhi Statue',
    shop_name: 'Royal Footwear & Bag World',
    biz_type: 'Footwear & Travel Luggage',
    biz_cat: 'Fashion & Footwear',
    shop_addr: 'No. 67, Town Hall Road',
    shop_area: 'Town Hall Road',
    shop_pincode: '636001',
    shop_landmark: 'Opposite State Bank Branch',
    years_biz: 15,
    income: 95000,
    sales: 18000,
    shop_photo: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-05',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10013',
    name: 'Deepa Venkatesh',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    gender: 'Female',
    dob: '1989-10-10',
    father_or_husband: 'Venkatesan P.',
    mother: 'Padma V.',
    marital: 'Married',
    mobile: '9843344557',
    email: 'deepa.xerox@gmail.com',
    door: '104',
    street: 'Chinnappa Nagar',
    area: 'Ammapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636003',
    landmark: 'Behind Corporation School',
    shop_name: 'Deepa Xerox, DTP & Online Services',
    biz_type: 'Digital Printing & CSC Center',
    biz_cat: 'Business Services',
    shop_addr: 'No. 15, Car Street',
    shop_area: 'Car Street',
    shop_pincode: '636002',
    shop_landmark: 'Near Court Entrance',
    years_biz: 8,
    income: 65000,
    sales: 12000,
    shop_photo: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL103',
    collector_name: 'Saravanan P.',
  },
  {
    id: 'KRS10014',
    name: 'Manikandan R.',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    gender: 'Male',
    dob: '1992-03-08',
    father_or_husband: 'Rathinam S.',
    mother: 'Meenakshi R.',
    marital: 'Single',
    mobile: '9843455668',
    email: 'murugan.fruits@gmail.com',
    door: '22/A',
    street: 'Thirunavukkarasu Street',
    area: 'Shevapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Railway Feeder Road',
    shop_name: 'Murugan Fruit Stall & Fresh Juice Corner',
    biz_type: 'Fresh Fruits & Juice Center',
    biz_cat: 'Food & Beverage',
    shop_addr: 'Stall No. 5, Market Gate',
    shop_area: 'Market Gate',
    shop_pincode: '636001',
    shop_landmark: 'Main Fruit Market Entrance',
    years_biz: 7,
    income: 75000,
    sales: 15000,
    shop_photo: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10015',
    name: 'Rajasekaran P.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'Male',
    dob: '1980-08-16',
    father_or_husband: 'Palanisamy K.',
    mother: 'Bagyam P.',
    marital: 'Married',
    mobile: '9843566779',
    email: 'raja.chips@gmail.com',
    door: '81',
    street: 'Meyyanur 2nd Street',
    area: 'Meyyanur',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636004',
    landmark: 'Near New Bus Stand Flyover',
    shop_name: 'Raja Cafe & Hot Chips Centre',
    biz_type: 'Snacks, Savouries & Hot Beverages',
    biz_cat: 'Food & Snacks',
    shop_addr: 'Shop 12, New Bus Stand South Wing',
    shop_area: 'New Bus Stand Area',
    shop_pincode: '636004',
    shop_landmark: 'Next to Aavin Milk Booth',
    years_biz: 12,
    income: 88000,
    sales: 17000,
    shop_photo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10016',
    name: 'Thangavel M.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    gender: 'Male',
    dob: '1976-11-28',
    father_or_husband: 'Marappa Gounder',
    mother: 'Pappathi M.',
    marital: 'Married',
    mobile: '9843677880',
    email: 'thangavel.pipes@gmail.com',
    door: '5/72',
    street: 'Old Edapadi Road',
    area: 'Shevapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Mariamman Kovil Ground',
    shop_name: 'Sri Murugan Iron Hardware & Pipes',
    biz_type: 'Iron & PVC Hardware Trading',
    biz_cat: 'Construction Materials',
    shop_addr: 'No. 95, Bazaar Main Road',
    shop_area: 'Bazaar Main Road',
    shop_pincode: '636001',
    shop_landmark: 'Opposite Muthu Complex',
    years_biz: 22,
    income: 180000,
    sales: 32000,
    shop_photo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500',
    plan_id: 'PLAN100_50K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10017',
    name: 'Balamurugan S.',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    gender: 'Male',
    dob: '1990-04-03',
    father_or_husband: 'Subramanian V.',
    mother: 'Gomathi S.',
    marital: 'Married',
    mobile: '9843788991',
    email: 'bala.mobiles@gmail.com',
    door: '28',
    street: 'Rajaji Street',
    area: 'Gugai',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636006',
    landmark: 'Near Gugai Sivan Temple',
    shop_name: 'Bala Mobile Store & Quick Service',
    biz_type: 'Smartphones & Repair Centre',
    biz_cat: 'Electronics & Mobiles',
    shop_addr: 'No. 38, Town Hall Road',
    shop_area: 'Town Hall Road',
    shop_pincode: '636001',
    shop_landmark: 'Near City Union Bank',
    years_biz: 7,
    income: 85000,
    sales: 16000,
    shop_photo: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10018',
    name: 'Shanmuga Sundaram',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    gender: 'Male',
    dob: '1978-02-19',
    father_or_husband: 'Sundaram Chettiar',
    mother: 'Kalyani S.',
    marital: 'Married',
    mobile: '9843899002',
    email: 'sundaram.timber@gmail.com',
    door: '62/4',
    street: 'Fort Main Road',
    area: 'Car Street',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    landmark: 'Behind Old Collectorate',
    shop_name: 'Sundaram Timber & Plywood Depot',
    biz_type: 'Timber & Interior Wood Materials',
    biz_cat: 'Wood & Construction',
    shop_addr: 'No. 112, Car Street',
    shop_area: 'Car Street',
    shop_pincode: '636002',
    shop_landmark: 'Near Kottai Perumal Temple',
    years_biz: 19,
    income: 210000,
    sales: 40000,
    shop_photo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500',
    plan_id: 'PLAN100_50K',
    start_date: '2026-07-01',
    collector_id: 'COL103',
    collector_name: 'Saravanan P.',
  },
  {
    id: 'KRS10019',
    name: 'Radha Krishnan',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    gender: 'Male',
    dob: '1984-12-11',
    father_or_husband: 'Krishnan Kutty',
    mother: 'Leela K.',
    marital: 'Married',
    mobile: '9843900113',
    email: 'radha.flowers@gmail.com',
    door: '14',
    street: 'Flower Bazaar Lane',
    area: 'Market Gate',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    landmark: 'Opposite Ganesha Temple',
    shop_name: 'Sri Radha Krishna Flower Market',
    biz_type: 'Fresh Garlands & Pooja Flowers',
    biz_cat: 'Florist & Religious Items',
    shop_addr: 'Stall #18, Flower Market Complex',
    shop_area: 'Market Gate',
    shop_pincode: '636001',
    shop_landmark: 'Near Central Arch',
    years_biz: 10,
    income: 68000,
    sales: 14000,
    shop_photo: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10020',
    name: 'Geetha Rani',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    gender: 'Female',
    dob: '1986-05-18',
    father_or_husband: 'Ravichandran N.',
    mother: 'Bhanumathi R.',
    marital: 'Married',
    mobile: '9844011224',
    email: 'geetha.books@gmail.com',
    door: '39',
    street: 'Teachers Colony',
    area: 'Alagapuram',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636016',
    landmark: 'Near CSI Matriculation School',
    shop_name: 'Saraswathi Book Center & Stationers',
    biz_type: 'School Books & Educational Items',
    biz_cat: 'Books & Stationeries',
    shop_addr: 'Shop 8, New Bus Stand Complex',
    shop_area: 'New Bus Stand Area',
    shop_pincode: '636004',
    shop_landmark: 'Near Reservation Counter',
    years_biz: 9,
    income: 72000,
    sales: 13500,
    shop_photo: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10021',
    name: 'Karthikeyan S.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'Male',
    dob: '1982-08-09',
    father_or_husband: 'Shanmugam Pillai',
    mother: 'Saradha S.',
    marital: 'Married',
    mobile: '9844122335',
    email: 'shiva.rice@gmail.com',
    door: '74',
    street: 'Chinna Kadai Veethi',
    area: 'Bazaar Main Road',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    landmark: 'Near Kannika Parameswari Kovil',
    shop_name: 'Shiva Sakthi Rice Mundy & Wholesale',
    biz_type: 'Rice, Dhall & Cereals Wholesale',
    biz_cat: 'Grain & Agro Produce',
    shop_addr: 'No. 56, Bazaar Main Road',
    shop_area: 'Bazaar Main Road',
    shop_pincode: '636001',
    shop_landmark: 'Near Grain Market Entry',
    years_biz: 16,
    income: 160000,
    sales: 30000,
    shop_photo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10022',
    name: 'Sivakumar M.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    gender: 'Male',
    dob: '1985-07-14',
    father_or_husband: 'Murugesan K.',
    mother: 'Dhanalakshmi M.',
    marital: 'Married',
    mobile: '9844233446',
    email: 'maruthi.cycle@gmail.com',
    door: '18/1',
    street: 'Gugai Pillaiyar Koil Street',
    area: 'Gugai',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636006',
    landmark: 'Opposite Municipal Dispensary',
    shop_name: 'Maruthi Cycle Works & Fitness Gears',
    biz_type: 'Bicycles, Kids Cycles & Repairs',
    biz_cat: 'Automotive & Fitness',
    shop_addr: 'No. 44, Town Hall Road',
    shop_area: 'Town Hall Road',
    shop_pincode: '636001',
    shop_landmark: 'Near Murugan Theatre',
    years_biz: 11,
    income: 78000,
    sales: 14500,
    shop_photo: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10023',
    name: 'Govindaraj K.',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    gender: 'Male',
    dob: '1987-10-31',
    father_or_husband: 'Kandasamy M.',
    mother: 'Rajammal K.',
    marital: 'Married',
    mobile: '9844344557',
    email: 'muruga.opticals@gmail.com',
    door: '109',
    street: 'Car Street 3rd Cross',
    area: 'Car Street',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Anjaneyar Kovil',
    shop_name: 'Om Muruga Optical & Eye Care',
    biz_type: 'Eyewear, Lenses & Frames',
    biz_cat: 'Healthcare & Optical',
    shop_addr: 'No. 29, Car Street',
    shop_area: 'Car Street',
    shop_pincode: '636002',
    shop_landmark: 'Opposite Sugavaneswarar Gopuram',
    years_biz: 8,
    income: 92000,
    sales: 17000,
    shop_photo: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL103',
    collector_name: 'Saravanan P.',
  },
  {
    id: 'KRS10024',
    name: 'Revathi Mohan',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    gender: 'Female',
    dob: '1988-06-20',
    father_or_husband: 'Mohanraj C.',
    mother: 'Vijayalakshmi M.',
    marital: 'Married',
    mobile: '9844455668',
    email: 'mohan.tailors@gmail.com',
    door: '27',
    street: 'Old Market Line',
    area: 'Market Gate',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    landmark: 'Behind Vegetable Stalls',
    shop_name: 'Mohan Tailors & Readymade Garments',
    biz_type: 'Gent & Ladies Tailoring Works',
    biz_cat: 'Fashion & Tailoring',
    shop_addr: 'No. 22, Market Gate',
    shop_area: 'Market Gate',
    shop_pincode: '636001',
    shop_landmark: 'Corner Shop, Cloth Merchant Row',
    years_biz: 10,
    income: 76000,
    sales: 14000,
    shop_photo: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10025',
    name: 'Arumugam P.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    gender: 'Male',
    dob: '1979-01-15',
    father_or_husband: 'Ponnan C.',
    mother: 'Chellammal P.',
    marital: 'Married',
    mobile: '9844566779',
    email: 'vasantham.tiffin@gmail.com',
    door: '58',
    street: 'Meyyanur Bypass Road',
    area: 'Meyyanur',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636004',
    landmark: 'Near Saravana Bhavan Hotel',
    shop_name: 'Vasantham Pure Veg Tiffin Center',
    biz_type: 'South Indian Fast Food & Tiffin',
    biz_cat: 'Restaurant & Eatery',
    shop_addr: 'Shop #2, Front Concourse, New Bus Stand',
    shop_area: 'New Bus Stand Area',
    shop_pincode: '636004',
    shop_landmark: 'Directly in front of Main Exit',
    years_biz: 14,
    income: 130000,
    sales: 25000,
    shop_photo: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10026',
    name: 'Vijayalakshmi N.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    gender: 'Female',
    dob: '1983-09-02',
    father_or_husband: 'Natarajan G.',
    mother: 'Mangalam N.',
    marital: 'Married',
    mobile: '9844677880',
    email: 'lakshmi.gold@gmail.com',
    door: '41',
    street: 'Agraharam Second Street',
    area: 'Shevapet',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Kannan Departmental Store',
    shop_name: 'Lakshmi Gold Covering & Fashion Jewels',
    biz_type: 'Fashion Jewellery & One-Gram Gold',
    biz_cat: 'Jewellery & Accessories',
    shop_addr: 'No. 31, Bazaar Main Road',
    shop_area: 'Bazaar Main Road',
    shop_pincode: '636001',
    shop_landmark: 'Next to Indian Bank ATM',
    years_biz: 12,
    income: 105000,
    sales: 19000,
    shop_photo: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10027',
    name: 'Dinesh Kumar',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    gender: 'Male',
    dob: '1994-04-12',
    father_or_husband: 'Kannan K.',
    mother: 'Pushpa K.',
    marital: 'Single',
    mobile: '9844788991',
    email: 'smart.cctv@gmail.com',
    door: '8',
    street: 'Gugai 4th Cross',
    area: 'Gugai',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636006',
    landmark: 'Near Gugai Community Hall',
    shop_name: 'Smart Computers & CCTV Security Solutions',
    biz_type: 'Computer Sales, CCTV & Networking',
    biz_cat: 'IT & Security Systems',
    shop_addr: 'No. 51, Town Hall Road',
    shop_area: 'Town Hall Road',
    shop_pincode: '636001',
    shop_landmark: 'Opposite Lic Office',
    years_biz: 6,
    income: 88000,
    sales: 16500,
    shop_photo: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
  {
    id: 'KRS10028',
    name: 'Padmavathi R.',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    gender: 'Female',
    dob: '1987-03-24',
    father_or_husband: 'Ramakrishnan P.',
    mother: 'Radhamani R.',
    marital: 'Married',
    mobile: '9844899002',
    email: 'padma.fancy@gmail.com',
    door: '93',
    street: 'Car Street 1st Lane',
    area: 'Car Street',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636002',
    landmark: 'Near Temple Chariot Shed',
    shop_name: 'Padmavathi Fancy & Plastic Home Goods',
    biz_type: 'Plasticware, Utensils & Novelties',
    biz_cat: 'Home Goods & General Store',
    shop_addr: 'No. 74, Car Street',
    shop_area: 'Car Street',
    shop_pincode: '636002',
    shop_landmark: 'Near South Car Gopuram',
    years_biz: 9,
    income: 70000,
    sales: 13000,
    shop_photo: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL103',
    collector_name: 'Saravanan P.',
  },
  {
    id: 'KRS10029',
    name: 'Kalaiselvan S.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'Male',
    dob: '1984-11-19',
    father_or_husband: 'Sengottaiyan A.',
    mother: 'Kamatchi S.',
    marital: 'Married',
    mobile: '9845011223',
    email: 'kumaran.bakery@gmail.com',
    door: '17',
    street: 'Old Market Gate Street',
    area: 'Market Gate',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636001',
    landmark: 'Behind Bus Shelter',
    shop_name: 'Sri Kumaran Bakery, Milk & Dairy',
    biz_type: 'Fresh Bakery, Cakes & Aavin Milk',
    biz_cat: 'Dairy & Confectionery',
    shop_addr: 'No. 3, Market Gate Road',
    shop_area: 'Market Gate',
    shop_pincode: '636001',
    shop_landmark: 'Opposite Auto Stand',
    years_biz: 11,
    income: 115000,
    sales: 21000,
    shop_photo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500',
    plan_id: 'PLAN100_20K',
    start_date: '2026-07-01',
    collector_id: 'COL101',
    collector_name: 'Murugan S.',
  },
  {
    id: 'KRS10030',
    name: 'Subhashini V.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    gender: 'Female',
    dob: '1991-07-07',
    father_or_husband: 'Vijayakumar S.',
    mother: 'Uma V.',
    marital: 'Married',
    mobile: '9845122334',
    email: 'krishna.organic@gmail.com',
    door: '29/B',
    street: 'Rajaji Salai',
    area: 'Fairlands',
    town: 'Salem',
    city: 'Salem',
    district: 'Salem',
    pincode: '636016',
    landmark: 'Near Saradha Grounds',
    shop_name: 'Krishna Organic Provisions & Millets',
    biz_type: 'Traditional Millets, Cold-Pressed Oils',
    biz_cat: 'Organic & Health Foods',
    shop_addr: 'Shop 15, New Bus Stand Shopping Plaza',
    shop_area: 'New Bus Stand Area',
    shop_pincode: '636004',
    shop_landmark: 'Near Plaza Main Entrance',
    years_biz: 8,
    income: 98000,
    sales: 18000,
    shop_photo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500',
    plan_id: 'PLAN100_10K',
    start_date: '2026-07-01',
    collector_id: 'COL102',
    collector_name: 'Karthik Raja',
  },
];

// Generate Full Database
console.log('Generating 30 customers and 3 months of historical data (July 1 to September 30, 2026)...');

const users = [
  {
    id: 'USR001',
    username: 'admin',
    email: 'admin@dailycollection.com',
    password: 'admin',
    role: 'ADMIN',
    name: 'Operations Admin',
    phone: '+91 94432 10001',
    is_active: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    created_at: '2026-01-01T09:00:00.000Z',
  },
  {
    id: 'USR005',
    username: 'COL101',
    email: 'murugan.collector@dailycollection.com',
    password: '1234',
    role: 'COLLECTOR',
    collector_id: 'COL101',
    name: 'Murugan S.',
    phone: '98421 11223',
    is_active: true,
    created_at: '2026-01-02T09:00:00.000Z',
  },
  {
    id: 'USR006',
    username: 'COL102',
    email: 'karthik.collector@dailycollection.com',
    password: '1234',
    role: 'COLLECTOR',
    collector_id: 'COL102',
    name: 'Karthik Raja',
    phone: '98422 33445',
    is_active: true,
    created_at: '2026-01-02T09:00:00.000Z',
  },
  {
    id: 'USR007',
    username: 'COL103',
    email: 'saravanan.collector@dailycollection.com',
    password: '1234',
    role: 'COLLECTOR',
    collector_id: 'COL103',
    name: 'Saravanan P.',
    phone: '98423 55667',
    is_active: true,
    created_at: '2026-01-02T09:00:00.000Z',
  },
];

const customers = [];
const customer_addresses = [];
const business_details = [];
const collection_accounts = [];
const documents = [];
const customer_notes = [];
const notifications = [];
const audit_logs = [];

const shopMargins = [10, 12, 15, 10, 12, 10, 15, 12, 10, 15, 12, 10, 15, 12, 10, 12, 15, 10, 12, 15, 10, 12, 15, 10, 12, 10, 15, 12, 10, 12];

customerDefinitions.forEach((def, idx) => {
  const custId = def.id;
  const userNum = String(idx + 1).padStart(3, '0');
  const marginPct = def.default_margin_percentage || shopMargins[idx % shopMargins.length];
  
  // User login for customer
  users.push({
    id: `USR_CUST_${custId}`,
    username: custId,
    email: def.email,
    password: '1234',
    role: 'CUSTOMER',
    customer_id: custId,
    name: def.name,
    phone: def.mobile,
    is_active: true,
    created_at: `${def.start_date}T10:00:00.000Z`,
  });

  // Customer Personal Details
  customers.push({
    id: custId,
    full_name: def.name,
    profile_photo: def.photo,
    gender: def.gender,
    dob: def.dob,
    father_or_husband_name: def.father_or_husband,
    mother_name: def.mother,
    marital_status: def.marital,
    mobile_number: def.mobile,
    alternate_number: def.mobile.slice(0, 8) + '99',
    whatsapp_number: def.mobile,
    email: def.email,
    status: 'ACTIVE',
    created_at: `${def.start_date}T10:00:00.000Z`,
    updated_at: '2026-09-30T10:00:00.000Z',
  });

  // Address
  customer_addresses.push({
    id: `ADDR${custId.slice(3)}`,
    customer_id: custId,
    door_number: def.door,
    street: def.street,
    area: def.area,
    village_or_town: def.town,
    city: def.city,
    district: def.district,
    state: 'Tamil Nadu',
    pincode: def.pincode,
    landmark: def.landmark,
  });

  // Business Details with variable Shop Margin % (Section 2 & 3)
  business_details.push({
    id: `SHP${custId.slice(3)}`,
    customer_id: custId,
    shop_name: def.shop_name,
    owner_name: def.name,
    business_type: def.biz_type,
    business_category: def.biz_cat,
    shop_mobile: def.mobile,
    shop_address: def.shop_addr,
    shop_area: def.shop_area,
    shop_city: def.city,
    shop_district: def.district,
    shop_pincode: def.shop_pincode,
    landmark: def.shop_landmark,
    years_in_business: def.years_biz,
    approx_monthly_income: def.income,
    approx_daily_sales: def.sales,
    default_margin_percentage: marginPct,
    business_status: 'ACTIVE',
    shop_photo: def.shop_photo,
  });

  // Collection Account with Permanent Margin Snapshot (Section 1, 4, 5, 8)
  const plan = collection_plans.find(p => p.id === def.plan_id) || collection_plans[0];
  const accId = `ACC-2026-${String(idx + 1).padStart(3, '0')}`;
  
  const reqAmount = plan.requested_amount;
  const marginAmount = safeRound(reqAmount * (marginPct / 100), 2);
  const disbAmount = safeRound(reqAmount - marginAmount, 2);
  const colDays = plan.collection_days;
  const totalRepay = reqAmount; // Customer repays the original requested amount
  const dailyDue = safeRound(totalRepay / colDays, 2);

  // Exact calendar math: start_date + (colDays - 1) days
  const [sY, sM, sD] = def.start_date.split('-').map(Number);
  const endUtc = new Date(Date.UTC(sY, sM - 1, sD + (colDays - 1)));
  const expectedEndDateStr = `${endUtc.getUTCFullYear()}-${String(endUtc.getUTCMonth() + 1).padStart(2, '0')}-${String(endUtc.getUTCDate()).padStart(2, '0')}`;

  collection_accounts.push({
    id: accId,
    customer_id: custId,
    customer_name: def.name,
    shop_name: def.shop_name,
    plan_id: plan.id,
    plan_name: plan.plan_name,
    requested_amount: reqAmount,
    margin_percentage: marginPct,
    margin_amount: marginAmount,
    disbursed_amount: disbAmount,
    daily_collection: dailyDue,
    collection_days: colDays,
    total_repayment: totalRepay,
    finance_margin: marginAmount,
    start_date: def.start_date,
    expected_end_date: expectedEndDateStr,
    amount_collected: 0, // will be calculated by running ledger
    remaining_amount: totalRepay, // will be calculated
    completed_days: 0,
    remaining_days: colDays,
    collection_percentage: 0,
    assigned_collector_id: def.collector_id,
    assigned_collector_name: def.collector_name,
    collection_area: def.shop_area,
    status: 'ACTIVE',
    created_at: `${def.start_date}T10:00:00.000Z`,
    updated_at: '2026-09-30T10:00:00.000Z',
  });

  // Documents
  documents.push({
    id: `DOC-${1000 + idx * 2 + 1}`,
    customer_id: custId,
    document_type: 'Aadhaar Card',
    document_number: `${Math.floor(1000 + Math.random() * 9000)} ${Math.floor(1000 + Math.random() * 9000)} ${Math.floor(1000 + Math.random() * 9000)}`,
    file_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600',
    file_name: `${custId.toLowerCase()}_aadhaar.jpg`,
    file_size: 450000 + (idx * 2300),
    mime_type: 'image/jpeg',
    upload_date: def.start_date,
    uploaded_by: `${def.collector_name} (${def.collector_id})`,
    verification_status: 'Verified',
    remarks: 'Original verified against UIDAI portal',
  });

  documents.push({
    id: `DOC-${1000 + idx * 2 + 2}`,
    customer_id: custId,
    document_type: idx % 3 === 0 ? 'Trade License' : (idx % 3 === 1 ? 'PAN Card' : 'Bank Passbook'),
    document_number: idx % 3 === 0 ? `SLM/CORP/SHP/2022/${1000 + idx}` : `ABCDE${1000 + idx}F`,
    file_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600',
    file_name: `${custId.toLowerCase()}_trade_proof.pdf`,
    file_size: 620000 + (idx * 5100),
    mime_type: 'application/pdf',
    upload_date: def.start_date,
    uploaded_by: `${def.collector_name} (${def.collector_id})`,
    verification_status: idx === 3 ? 'Pending Verification' : 'Verified',
  });

  // Notes
  customer_notes.push({
    id: `NOTE-${100 + idx}`,
    customer_id: custId,
    note: `Retail verification completed for ${def.shop_name}. Footfall is steady, daily sales approx ₹${def.sales.toLocaleString('en-IN')}. Good credit profile.`,
    created_by: `${def.collector_name} (Collector)`,
    created_at: `${def.start_date}T16:00:00.000Z`,
  });
});

// Update Area counts accurately
areas.forEach(area => {
  area.customer_count = collection_accounts.filter(a => a.collection_area === area.area_name).length;
});

// 5. Generate 3 MONTHS of daily collections (July 1 to September 30, 2026)
const daily_collections = [];
const payments = [];
const receipts = [];

let receiptSeq = 1001;
let paySeq = 1001;

// Maintain running ledger for each account
const accountLedgers = {};
collection_accounts.forEach(acc => {
  accountLedgers[acc.id] = {
    runningBalance: acc.total_repayment,
    totalCollected: 0,
    paidDaysCount: 0,
  };
});

// Date list from July 1, 2026 to September 30, 2026 (92 days)
const allDates = [];

// Helper to format date YYYY-MM-DD
function getDateString(year, month, day) {
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

// July (1 to 31)
for (let d = 1; d <= 31; d++) allDates.push(getDateString(2026, 7, d));
// August (1 to 31)
for (let d = 1; d <= 31; d++) allDates.push(getDateString(2026, 8, d));
// September (1 to 30)
for (let d = 1; d <= 30; d++) allDates.push(getDateString(2026, 9, d));

console.log(`Simulating daily collections across ${allDates.length} days for ${collection_accounts.length} retail accounts...`);

allDates.forEach((dateStr, dateIdx) => {
  const isToday = dateStr === '2026-09-30';
  const dayOfMonth = parseInt(dateStr.slice(8, 10), 10);
  const monthNum = parseInt(dateStr.slice(5, 7), 10);

  collection_accounts.forEach((acc, accIdx) => {
    // Only collect if account has started on or before this date
    if (dateStr < acc.start_date) return;

    // Check if account has already been fully paid
    const ledger = accountLedgers[acc.id];
    if (ledger.runningBalance <= 0) return;

    const dailyDue = acc.daily_collection;
    let status = 'PAID';
    let paid = dailyDue;
    let pending = 0;
    let advance = 0;
    let reason = undefined;

    // Realistic behavior patterns based on customer index and day
    // Customer 4 (Vijay Anand) missed some days in June/July/Aug/Sept
    if (acc.customer_id === 'KRS10004' && (dayOfMonth === 5 || dayOfMonth === 15 || dayOfMonth === 22)) {
      status = 'MISSED';
      paid = 0;
      pending = dailyDue;
      reason = 'Shop closed for stock arrival / maintenance';
    } else if (acc.customer_id === 'KRS10014' && dayOfMonth === 12) {
      status = 'MISSED';
      paid = 0;
      pending = dailyDue;
      reason = 'Out of station for fruit mandi purchase';
    } else if (acc.customer_id === 'KRS10001' && (dayOfMonth === 10 && monthNum === 8)) {
      // Advance payment on festival
      status = 'ADVANCE';
      paid = dailyDue * 3;
      advance = dailyDue * 2;
      reason = 'Aadi festival advance collection';
    } else if (acc.customer_id === 'KRS10002' && (dayOfMonth === 25 && monthNum === 8)) {
      status = 'ADVANCE';
      paid = dailyDue * 2;
      advance = dailyDue;
      reason = 'Advance payment before weekend';
    } else if ((accIdx + dayOfMonth) % 37 === 0) {
      // Sporadic partial payment
      status = 'PARTIAL';
      paid = safeRound(dailyDue * 0.5, 2);
      pending = safeRound(dailyDue * 0.5, 2);
      reason = 'Partial payment - balance promised next round';
    } else if ((accIdx + dayOfMonth) % 43 === 0) {
      // Sporadic missed payment
      status = 'MISSED';
      paid = 0;
      pending = dailyDue;
      reason = 'Shop owner away at wholesale market';
    }

    // For today (September 30, 2026), simulate field collection in progress:
    // First 18 customers already collected today, remaining 12 are PENDING today so collector has work to do!
    if (isToday) {
      if (accIdx >= 18) {
        status = 'PENDING';
        paid = 0;
        pending = dailyDue;
        reason = undefined;
      }
    }

    // Cap paid amount by remaining balance
    paid = Math.min(paid, ledger.runningBalance);

    const prevBalance = ledger.runningBalance;
    const newRemainingBalance = Math.max(0, safeRound(prevBalance - paid, 2));

    if (paid > 0) {
      ledger.runningBalance = newRemainingBalance;
      ledger.totalCollected = safeRound(ledger.totalCollected + paid, 2);
      ledger.paidDaysCount += (paid >= dailyDue ? Math.floor(paid / dailyDue) : 0.5);
    }

    const recId = `REC-${dateStr}-${acc.customer_id}`;
    const recNumber = `DC-REC-2026-${String(receiptSeq++).padStart(5, '0')}`;
    const paymentMode = paid > 0 ? (accIdx % 2 === 0 ? 'Cash' : 'UPI') : undefined;

    const [stY, stM, stD] = acc.start_date.split('-').map(Number);
    const [curY, curM, curD] = dateStr.split('-').map(Number);
    const sUtc = Date.UTC(stY, stM - 1, stD);
    const cUtc = Date.UTC(curY, curM - 1, curD);
    const dayNumber = Math.round((cUtc - sUtc) / (1000 * 60 * 60 * 24)) + 1;

    const dailyRec = {
      id: `DC-${dateStr}-${acc.id}`,
      collection_account_id: acc.id,
      customer_id: acc.customer_id,
      customer_name: acc.customer_name,
      shop_name: acc.shop_name || '',
      mobile_number: customers.find(c => c.id === acc.customer_id)?.mobile_number || '',
      collection_day_number: dayNumber,
      calendar_date: dateStr,
      date: dateStr,
      daily_due: dailyDue,
      paid_amount: paid,
      pending_amount: pending,
      advance_amount: advance,
      status: status,
      payment_mode: paymentMode,
      collector_id: acc.assigned_collector_id,
      collector_name: acc.assigned_collector_name,
      collection_area: acc.collection_area,
      reason: reason,
      remarks: reason ? reason : (paid > 0 ? 'Collected on field' : 'Pending collector round'),
      receipt_id: paid > 0 ? recId : undefined,
      receipt_number: paid > 0 ? recNumber : undefined,
      balance_remaining: paid > 0 ? newRemainingBalance : prevBalance,
    };
    daily_collections.push(dailyRec);

    if (paid > 0) {
      const paymentId = `PAY-2026-${String(paySeq++).padStart(5, '0')}`;
      payments.push({
        id: paymentId,
        receipt_number: recNumber,
        collection_account_id: acc.id,
        customer_id: acc.customer_id,
        customer_name: acc.customer_name,
        shop_name: acc.shop_name || '',
        collection_date: dateStr,
        daily_due: dailyDue,
        amount_paid: paid,
        advance_amount: advance,
        payment_mode: paymentMode,
        collector_id: acc.assigned_collector_id,
        collector_name: acc.assigned_collector_name,
        previous_balance: prevBalance,
        remaining_balance: newRemainingBalance,
        status: advance > 0 ? 'ADVANCE' : (pending > 0 ? 'PARTIAL' : 'SUCCESS'),
        transaction_ref: paymentMode === 'UPI' ? `UPI${Math.floor(1000000000 + Math.random() * 9000000000)}` : undefined,
        remarks: reason || 'Daily collection installment',
        created_at: `${dateStr}T11:${String((accIdx * 2) % 50).padStart(2, '0')}:00.000Z`,
      });

      receipts.push({
        id: recId,
        receipt_number: recNumber,
        payment_id: paymentId,
        collection_account_id: acc.id,
        customer_id: acc.customer_id,
        customer_name: acc.customer_name,
        shop_name: acc.shop_name || '',
        daily_due: dailyDue,
        amount_paid: paid,
        payment_mode: paymentMode,
        previous_balance: prevBalance,
        remaining_balance: newRemainingBalance,
        collector_name: acc.assigned_collector_name,
        date: dateStr,
        created_at: `${dateStr}T11:${String((accIdx * 2) % 50).padStart(2, '0')}:00.000Z`,
        remarks: 'Thank you for your timely payment.',
      });
    }
  });
});

// Section 10 & 11: Schedule upcoming remaining days (e.g. Days 93-100 in October 2026) for continuous 100-day cycle
collection_accounts.forEach(acc => {
  const [stY, stM, stD] = acc.start_date.split('-').map(Number);
  const sUtc = Date.UTC(stY, stM - 1, stD);
  const alreadyScheduledCount = daily_collections.filter(d => d.collection_account_id === acc.id).length;

  for (let dayNum = alreadyScheduledCount + 1; dayNum <= acc.collection_days; dayNum++) {
    const fUtc = new Date(sUtc + (dayNum - 1) * 86400000);
    const dateStr = `${fUtc.getUTCFullYear()}-${String(fUtc.getUTCMonth() + 1).padStart(2, '0')}-${String(fUtc.getUTCDate()).padStart(2, '0')}`;

    const futureRec = {
      id: `DC-${dateStr}-${acc.id}`,
      collection_account_id: acc.id,
      customer_id: acc.customer_id,
      customer_name: acc.customer_name,
      shop_name: acc.shop_name || '',
      mobile_number: customers.find(c => c.id === acc.customer_id)?.mobile_number || '',
      collection_day_number: dayNum,
      calendar_date: dateStr,
      date: dateStr,
      daily_due: acc.daily_collection,
      paid_amount: 0,
      pending_amount: acc.daily_collection,
      advance_amount: 0,
      status: 'PENDING',
      collector_id: acc.assigned_collector_id,
      collector_name: acc.assigned_collector_name,
      collection_area: acc.collection_area,
      remarks: 'Scheduled doorstep collection installment',
      balance_remaining: acc.remaining_amount,
    };

    daily_collections.push(futureRec);
  }
});

// Finalize collection accounts summaries
collection_accounts.forEach(acc => {
  const ledger = accountLedgers[acc.id];
  acc.amount_collected = safeRound(ledger.totalCollected, 2);
  acc.remaining_amount = safeRound(ledger.runningBalance, 2);
  acc.completed_days = Math.floor(acc.amount_collected / acc.daily_collection);
  acc.remaining_days = Math.max(0, acc.collection_days - acc.completed_days);
  acc.collection_percentage = safeRound((acc.amount_collected / acc.total_repayment) * 100, 1);
  
  if (acc.remaining_amount <= 0) {
    acc.status = 'COMPLETED';
  } else if (acc.expected_end_date < '2026-09-30') {
    acc.status = 'OVERDUE';
  } else {
    acc.status = 'ACTIVE';
  }
});

// Notifications
notifications.push(
  {
    id: 'NOTIF-01',
    recipient_role: 'ADMIN',
    title: 'Daily Collections Active',
    message: '30 accounts active across 5 areas for September 30, 2026.',
    type: 'SYSTEM',
    is_read: false,
    created_at: '2026-09-30T09:00:00.000Z',
  },
  {
    id: 'NOTIF-02',
    recipient_role: 'ADMIN',
    title: 'Monthly Collection Target Surpassed',
    message: 'Quarterly collection cycle for July, August, September has reached over ₹8.5 Lakhs.',
    type: 'PAYMENT',
    is_read: false,
    created_at: '2026-09-30T08:30:00.000Z',
  }
);

// Audit logs
audit_logs.push({
  id: `AUDIT-INIT-${Date.now()}`,
  user: 'admin',
  role: 'ADMIN',
  action: 'INITIALIZE_30_CUSTOMERS_AND_3_MONTHS',
  record_id: 'ALL',
  record_type: 'system',
  previous_value: null,
  new_value: { customers: customers.length, accounts: collection_accounts.length, payments: payments.length },
  timestamp: new Date().toISOString(),
});

const completeDatabase = {
  users,
  customers,
  customer_addresses,
  business_details,
  collection_plans,
  collection_accounts,
  daily_collections,
  payments,
  receipts,
  collectors,
  areas,
  documents,
  notifications,
  customer_notes,
  audit_logs,
  settings,
};

// Write out to krs_finance_data.json
const jsonString = JSON.stringify(completeDatabase, null, 2);
const dbPath = path.resolve(__dirname, '..', 'krs_finance_data.json');
const backupPath = path.resolve(__dirname, '..', 'krs_finance_data.backup.json');

fs.writeFileSync(dbPath, jsonString, 'utf-8');
fs.writeFileSync(backupPath, jsonString, 'utf-8');

console.log('✅ Successfully generated and written krs_finance_data.json!');
console.log({
  users: users.length,
  customers: customers.length,
  accounts: collection_accounts.length,
  daily_collections: daily_collections.length,
  payments: payments.length,
  receipts: receipts.length,
  areas: areas.length,
  collectors: collectors.length,
});
